### ISSUE TITLE
Define Widgets in THEME for ease of UI building.

### ISSUE THREAD

**Issue by TheOlajos** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#12]
Widgets can be defined in theme for use and reuse without defining multiple attributes. Attributes defined or set in templates will override THEME attributes.

Example in theme: <BOX id="b1" color="red, green" borderwidth="20"> will pass those attributes to any widget themed as such.

All widgets will take theme="{theme.ID}", or theme={ID} (in this case it will find a widget within the same template).

**Comment by TheOlajos** [comment]
Currently in progress as PROTOTYPE/STYLE

**Comment by BrayFlex** [comment]
Because now there is only 1 THEME lets create a new issue with prototype as the main topic
