### ISSUE TITLE
Feature Requestion: FML Pad

### ISSUE THREAD

**Issue by csells** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#122]
FML has a ton of potential and, because it's a language that provides a dynamic UI via interpretation and not compilation, it's begging for a tool that lets me just type FML into one pane and see the rendered result in another pane. In the WPF world, we used to call this "XAML Pad". Of course, you're already familiar with DartPad. Where's FML Pad? Why isn't the home page for fml.dev just an instance of FML Pad that gets me going on exploring the beauty and wonder that is FML w/in minutes of me landing on the site?

**Comment by TheOlajos** [comment]
Hi csells! we actually have the ability to quickly create one of those within our home page. I will double check that we can do it securely and then implement it next week! 

Thanks for the comment we really appreciate it.

**Comment by BrayFlex** [comment]
> FML has a ton of potential and, because it's a language that provides a dynamic UI via interpretation and not compilation, it's begging for a tool that lets me just type FML into one pane and see the rendered result in another pane. In the WPF world, we used to call this "XAML Pad". Of course, you're already familiar with DartPad. Where's FML Pad? Why isn't the home page for fml.dev just an instance of FML Pad that gets me going on exploring the beauty and wonder that is FML w/in minutes of me landing on the site?

We've been trying to determine a way to get people into building FML. Our solution thus far was to package a localhost capable version. I think this is a better idea, at least to let people try it. It would provide faster access in a simple, familiar way and I think you're correct it should be right on the home page. 

Great suggestion, thanks!

**Comment by TheOlajos** [comment]
@csells we have created FMLPAD with the latest version of FML (built in FML), but to enhance its use we have added an EDITOR widget that allows for an easy code editor to be built within FML apps. This will ship with the next release and has been merged into master. I will let you know when we publish the release on our main page and in the app stores.

**Comment by csells** [comment]
Great! Can't wait to try it.
