### ISSUE TITLE
THEME colors should be consistently used by default.

### ISSUE THREAD

**Issue by TheOlajos** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#16]
Theme colors should be consistent as defaults across the application. The application should always use theme colors as the default color values. 

Allow a user to define theme colors in the theme outside of defaults like we do with INCLUDE since widgets will be able to be defined. USE VARS or create a new var type called COLOR

**Comment by BrayFlex** [comment]
https://github.com/AppDaddy-Software-Solutions-Inc/fml/pull/607 ?
