### ISSUE TITLE
Allow regex() event to take invalid chars, allow input allow and deny to take full regex as well. 

### ISSUE THREAD

**Issue by TheOlajos** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#25]
Currently the regex event does not allow for invalid chars such as /

**Comment by BrayFlex** [comment]
We can't support full regex on input's allow/deny because a user can only type 1 character at a time so complex regex would fail. It would be more appropriate as an alarm.

**Comment by BrayFlex** [comment]
> Currently the regex event does not allow for invalid chars such as /

is this because `/` is divide?
