### ISSUE TITLE
Custom Controlled Databroker for intertemplate handling.

### ISSUE THREAD

**Issue by TheOlajos** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#26]
Allow a databroker to have pop(), push(), append(), prepend(), insert(), replace(), remove() and delete() events for use with intertemplate items like camera. These events will also work for items like NFC and barcode. This would allow you to generate grids without saving to an api or locally, etc. 

potential call would be url="template://"

**Comment by BrayFlex** [comment]
The ideas presented here are largely implemented although in a different way since datasources have changed so much
