### ISSUE TITLE
All http datasource documentation indicates to incorrectly use <HEADERS />

### ISSUE THREAD

**Issue by BrayFlex** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#316]
The documentation mentions in multiple places to modify a http datasource header to do soemthing like:

```xml
<HEADERS>
    <HEADER key="" value="">
</HEADERS>
```

it also mentions an empty `<HEADERS />` tag to avoid sending headers.

The code does not support this wrapper, it only works with `<HEADER ... />` within a http datasource.

What solution do you want to support @JeffOlajos

**Comment by TheOlajos** [comment]
@JeffOlajos fixed these inconsistencies
