### ISSUE TITLE
Input, Select, Typeahead Datepicker design needs improvement

### ISSUE THREAD

**Issue by BrayFlex** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#321]
The Input, Select and Typeahead all have slightly different layouts and should be more uniform. 

They should also have a slightly offcolor background to help indicate to the user they are interactable but can be set to transparent. 

The design attributes should be modified to be consistent with the name/value that other widgets within fml use (ie instead of `border="underline"` use `border="bottom"`).

We should also refactor the code and clean up the variations of each within the view.

Below is a column of 3 select variations followed by 2 typeahead variations for reference.

<img width="134" alt="image" src="https://user-images.githubusercontent.com/33260515/231180666-98f95572-249c-4cdc-a6e2-9c6dbd61f673.png"><img width="131" alt="image" src="https://user-images.githubusercontent.com/33260515/231185705-fd65c3eb-988d-4f13-a532-fed9251cca6f.png">

**Comment by TheOlajos** [comment]
Will do this with the remainder of form stuff tomorrow.

**Comment by TheOlajos** [comment]
I have made these consistent, including updated (less gawdy) error states, equality in spacing and sizing with all border and hint styles, and ensuring as many attributes as possible work together while maintaining this equality.
