### ISSUE TITLE
Migrate from to Flutters Date/Time Picker

### ISSUE THREAD

**Issue by BrayFlex** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#327]
The datetime formfield package (https://github.com/jifalops/datetime_picker_formfield) we use is discontinued it also blocks us from updating the intl package so I propose we need to build our own from flutter's functions:
https://api.flutter.dev/flutter/material/showDatePicker.html
https://api.flutter.dev/flutter/material/showDateRangePicker.html
https://api.flutter.dev/flutter/material/CalendarDatePicker-class.html
https://api.flutter.dev/flutter/material/showTimePicker.html

**Comment by TheOlajos** [comment]
This was resolved, the branches are cleaned
