### ISSUE TITLE
POPOVER children enhancements

### ISSUE THREAD

**Issue by TheOlajos** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#35]
Popover's item currently does not allow for children, and only a label is available. Popover should be able to be sized to its children, possible take a databroker like other item and option based widgets, and allow for any widgets within reason to be children of ITEM

**Comment by BrayFlex** [comment]
I would say popover could use some enhancements, being able to derive children from a datasource broker is always good. However a popover is not meant to be customized, perhaps we could add an optional icon to it so that it is more visual but it loses its purpose with custom children widgets.

**Comment by TheOlajos** [comment]
Popover can now take children
