### ISSUE TITLE
Long initial load time FML Web

### ISSUE THREAD

**Issue by TheOlajos** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#51]
The FML web version initial load time without the application cached can take up to 3 minutes on a slow connection. We need to consider:

-Loading in only parts of the app that are needed.
- Allowing devs to specify what is loaded in at what point potentially in the config?

**Comment by BrayFlex** [comment]
We have reduced this by almost 2/3rds down from ~9mb main.dart.js to ~3mb by using deferred loading on the web #73
