### ISSUE TITLE
Long text blocks on mobile-web cause scroll jank

### ISSUE THREAD

**Issue by BrayFlex** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#53]
Title describes as much as we know about this issue, it doesn't seem that ios/android device matters, just that its mobile-web.

Breaking the large text block up into smaller ones as a workaround prevents the issue.

**Comment by TheOlajos** [comment]
https://github.com/flutter/flutter/issues/32338

This is a flutter html renderer issue and does not seem to be present on web builds with canvaskit.

**Comment by TheOlajos** [comment]
Other widgets causing jank could be related to this open issue as well:

https://github.com/flutter/flutter/issues/52207
