### ISSUE TITLE
Date/Time Picker 

### ISSUE THREAD

**Issue by Caden-Dees** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#643]
On selection of a new date, time is set to the current time instead of the previous time.  For example if I have 5/3/24 8:00:00 selected, when I go to change it to 5/1/24 the time is automatically brought to the most recent time 10:23:45, there should be an option to default it to previous so with less clicks it can be 5/1/24 8:00:00.

**Comment by JeffOlajos** [comment]
This is fixed and will be in the next build.

**Comment by JeffOlajos** [comment]
Done.
