### ISSUE TITLE
Chart Sizing Not Updating

### ISSUE THREAD

**Issue by Caden-Dees** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#646]
When binding max/min of the y-axis of a chart, it updates the value but does not reflect on the chart visually (the chart doesn't rebuild with the changed value).  For example an input widget with value of 100 is changed to 50 and has an onchange="yaxisid.max.set({maxinput})" updates the value of yaxisid.max to 50 (verified by using a text displaying that value) but the chart yaxis still shows 100.

**Comment by TheOlajos** [comment]
This is fixed with the upcoming chart update branch
