### ISSUE TITLE
Addempty & Option with type="empty" Conflict

### ISSUE THREAD

**Issue by SomeGoodYear11** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#670]
When adding an empty option choice, data is loaded with an additional blank choice. However, setting addempty equal to false within the widget to combat that, completely removes the empty Option choice.

**Comment by TheOlajos** [comment]
This will be fixed in the upcoming merge

**Comment by TheOlajos** [comment]
Diving further into this it is already working in the main branch. There is a possibility your return data adds an empty option on its own, in which case you can add a label to the null value.
