### ISSUE TITLE
Widget Tip

### ISSUE THREAD

**Issue by SomeGoodYear11** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#671]
Tip/tooltip attribute isn't functional

**Comment by TheOlajos** [comment]
working on

**Comment by TheOlajos** [comment]
This seems to be working on the widgets I have tested it on. Do you have a further example of where you are not seeing it work, using tip=""

**Comment by SomeGoodYear11** [comment]
This issue seems to be resolved.
