### ISSUE TITLE
Checkbox - Setting an Initial State

### ISSUE THREAD

**Issue by libbyblanchard3** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#674]
Unable to set checkbox to an initial state so that it would be checked. The attached images were tests that did not work.

![checkbox1](https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/assets/169904654/3fea52c9-730b-4acf-ab67-a84022c2e36a)
![checkbox2](https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/assets/169904654/4cad2aa4-4fbf-4a76-8584-7f0c2098abee)
![image](https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/assets/169904654/043ad1aa-567c-4f3e-9ac5-540eebbc00ea)

**Comment by JeffOlajos** [comment]
I have a fix.  Will put on the test box tomorrow morning.

Thanks,
Jeff
