### ISSUE TITLE
.selected Recognizes Removed Rows

### ISSUE THREAD

**Issue by libbyblanchard3** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#681]
.selected continues to recognize a selected row once it is removed...

In my case, I am using .selected to set a variable for the rowID of a row, then pass that variable into my delete post call. The problem arises that once the selected row has been removed it is still recognized as an existing row, so when I use .selected again without selecting a new row, the removed row is recognized, which no longer exists.

Here is what my code looks like...

To remove the row I am setting the variable row_id_val onclick of the remove button on the side of the page. Then I pass that variable into my delete post call. And the post is ran when the user selects 'Yes' in the modal that asks the user to verify the row they want to delete

![image](https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/assets/169904654/e359c68f-9d84-4c65-a20a-f6af2ca32953)
![image](https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/assets/169904654/fb67e01e-b1e7-46ae-a035-2e2dfe14fcf0)
![image](https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/assets/169904654/032cab12-a4c9-4873-84c6-2a52b5ea5549)
![image](https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/assets/169904654/11ff70ca-f116-4dcd-9750-a94e2df5a7c1)

On success of the delete post call the datasources tied to the table are started.

![image](https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/assets/169904654/193354aa-720a-439d-80b7-2bc2bbdbd5f8)

**Comment by TheOlajos** [comment]
This is fixed in the connected branch
