### ISSUE TITLE
Iterative Posting Fault in Table Widget

### ISSUE THREAD

**Issue by libbyblanchard3** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#682]
We would like to be able to iteratively post all changed data in a table. By this I mean that if multiple data fields are changed in a table, we would like to, on trigger, be able to iteratively post the changed fields to update the backend.

There is a bug in the table widget that was formed from the most recent FML update that does not allow the post functionality to be ran iteratively when placed inside the table row <TR>. 

The following code is what we have developed, and it is not providing correct functionality. 

![image](https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/assets/169904654/95a5a32b-e0f5-4d83-a6d9-1cafe2c104d7)
![image](https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/assets/169904654/d8fa225e-a9c8-4157-a433-a2e5691e6c02)
![image](https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/assets/169904654/52903e84-0963-42d6-a194-d1f831c2cf9b)

**Comment by JeffOlajos** [comment]
Hi Libby,

Where can I find this page? How do I navigate to it and on which server? I
want to test with my mods.

Thanks,
Jeff

**Comment by libbyblanchard3** [comment]
I'm writing this page for MASDA not the GYMenu so it would be the 127.0.0.1:81 server if you have access. It is the dictionary_maintenance.xml page. I will attach a text file with the code and query file
[dictionary_maintenance.txt](https://github.com/user-attachments/files/16178741/dictionary_maintenance.txt)
[DictionaryMaintenance.txt](https://github.com/user-attachments/files/16178742/DictionaryMaintenance.txt)

**Comment by TheOlajos** [comment]
This seems to be an issue when using custom formfield widgets, which do not mark the row as dirty when edited.

**Comment by TheOlajos** [comment]
We are working on all issues with table today. That should clear the current issue board.
