### ISSUE TITLE
min/max height/width are not being respected on box

### ISSUE THREAD

**Issue by BrayFlex** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#76]
They work with row/column it seems but not box. checkbox-example has a working min height on its row but if changed to a box and expand="false" it doesn't respect the min height.

You can see this by checking months and watching the column grow from min but if changes to a box it doesn't start at its min height
https://fml.appdaddy.co/#/assets/templates/examples/checkbox-example1.xml

**Comment by TheOlajos** [comment]
This should be fixed #105
