### ISSUE TITLE
TEXT's markdown syntax has some inconsistencies 

### ISSUE THREAD

**Issue by BrayFlex** [AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language#86]
Some issues we have around inline markup:
Markup syntax requires a space before,

Either we need a library to parse the markdown or to improve our parser

**Comment by TheOlajos** [comment]
I am looking to convert our Text to the flutter_markdown package.

**Comment by BrayFlex** [comment]
Might be easier to use the dart https://pub.dev/packages/markdown and take the parsed tree values and convert them into our spans since the flutter_markdown creates its own markdown widget
